services:
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    container_name: broker
    networks:
      - msg_network

  servidor:
    build:
      context: .
      dockerfile: servidor/Dockerfile
    deploy:
      replicas: 2 
    depends_on:
      - broker
    networks:
      - msg_network

  cliente:
    build:
      context: .
      dockerfile: cliente/Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - broker 
    networks:
      - msg_network

networks:
  msg_network:
    driver: bridge
