services: 
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    container_name: broker
    networks:
      - msg_network

  proxy_pubsub:
    build:
      context: ./proxy_pubsub
      dockerfile: Dockerfile
    container_name: proxy_pubsub
    networks:
      - msg_network

  servidor1:
    build:
      context: .
      dockerfile: servidor/Dockerfile
    container_name: servidor1
    environment:
      - SERVER_ID=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data_srv1:/app/data
    depends_on:
      - broker
    networks:
      - msg_network

  servidor2:
    build:
      context: .
      dockerfile: servidor/Dockerfile
    container_name: servidor2
    environment:
      - SERVER_ID=2
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data_srv2:/app/data
    depends_on:
      - broker
    networks:
      - msg_network

  cliente1:
    build:
      context: .
      dockerfile: cliente/Dockerfile
    container_name: cliente1
    environment:
      - BOT_NAME=Bot_Alpha
    depends_on:
      - broker
    networks:
      - msg_network

  cliente2:
    build:
      context: .
      dockerfile: cliente/Dockerfile
    container_name: cliente2
    environment:
      - BOT_NAME=Bot_Beta
    depends_on:
      - broker
    networks:
      - msg_network

  referencia:
    build:
      context: ./referencia
      dockerfile: Dockerfile
    container_name: referencia
    networks:
      - msg_network

networks:
  msg_network:
    driver: bridge
